version: "3.8"
services:
  postgres:
    image: docker.io/library/postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=johnstack
    ports:
      - "5000:5432"
    volumes:
      - ../../migrations:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
